using PeachImage.Formats.Tiff.Decoding;

namespace PeachImage.Tests.Formats.Tiff.Unit.Decoding;

public class TiffLzwDecoderTests
{
    /// <summary>
    /// Hand-computed, not generated by <see cref="TiffLzwTestEncoder"/>: encodes "AAA" as
    /// Clear(256), 65, 258, EOI(257) — each a 9-bit MSB-first code, packed into 5 bytes
    /// (0x80, 0x10, 0x60, 0x50, 0x10) — and traces through TIFF's exact rules (ClearCode=256,
    /// EndCode=257, first free code=258, literal codes 0-255 are raw byte values) independently of both
    /// the production decoder and the test encoder, so it can't share a bug with either.
    /// </summary>
    [Fact]
    public void Decode_HandComputedThreeRepeatedBytes_MatchesOriginal()
    {
        byte[] compressed = [0x80, 0x10, 0x60, 0x50, 0x10];
        var output = new byte[3];

        TiffLzwDecoder.Decode(compressed, output);

        Assert.Equal([65, 65, 65], output);
    }

    [Fact]
    public void Decode_RoundTripsShortLiteralRun()
    {
        byte[] input = "Hello, TIFF!"u8.ToArray();
        AssertRoundTrips(input);
    }

    [Fact]
    public void Decode_RoundTripsLongRepeatedRun_ExercisesTableGrowth()
    {
        var input = new byte[5000];
        Array.Fill(input, (byte)'A');
        AssertRoundTrips(input);
    }

    [Fact]
    public void Decode_RoundTripsPseudoRandomData_CrossesEarlyChangeThresholds()
    {
        var random = new Random(12345);
        var input = new byte[20000];
        random.NextBytes(input);

        // A few repeated substrings so the table actually grows past the 511/1023/2047 "early change"
        // thresholds rather than degenerating into all-literal codes.
        for (int i = 0; i < input.Length - 8; i += 37)
        {
            input[i + 4] = input[i];
            input[i + 5] = input[i + 1];
            input[i + 6] = input[i + 2];
            input[i + 7] = input[i + 3];
        }

        AssertRoundTrips(input);
    }

    [Fact]
    public void Decode_RoundTripsAcrossMultipleClears()
    {
        // Force several Clear codes' worth of data by round-tripping many independent short runs
        // concatenated together, which is how a real multi-strip LZW-compressed TIFF's per-strip streams
        // each independently reset the table.
        var input = new List<byte>();
        for (int i = 0; i < 20; i++)
        {
            input.AddRange("The quick brown fox jumps over the lazy dog. "u8.ToArray());
        }

        AssertRoundTrips(input.ToArray());
    }

    [Fact]
    public void Decode_TruncatedStream_StopsGracefullyWithoutThrowing()
    {
        byte[] compressed = TiffLzwTestEncoder.Encode("Hello, TIFF!"u8.ToArray());
        byte[] truncated = compressed[..(compressed.Length / 2)];
        var output = new byte[64];

        var exception = Record.Exception(() => TiffLzwDecoder.Decode(truncated, output));

        Assert.Null(exception);
    }

    [Fact]
    public void Decode_EmptyOutput_DoesNothing()
    {
        var exception = Record.Exception(() => TiffLzwDecoder.Decode([0x80, 0x10], []));

        Assert.Null(exception);
    }

    private static void AssertRoundTrips(byte[] input)
    {
        byte[] compressed = TiffLzwTestEncoder.Encode(input);
        var output = new byte[input.Length];

        TiffLzwDecoder.Decode(compressed, output);

        Assert.Equal(input, output);
    }
}
