<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>PeachImage.Benchmarks</RootNamespace>
    <NoWarn>$(NoWarn);CS1591;CA1707;CA1001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Quamotion.TurboJpegWrapper" Version="2.0.32" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PeachImage\PeachImage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
